// Material definitions for different visual styles
export const materialOptions = {
  glass: {
    metalness: 0.2,
    roughness: 0.1,
    transmission: 0.9,
    thickness: 0.5,
    ior: 1.5,
    transparent: true,
    opacity: 0.6,
    envMapIntensity: 1.0,
    clearcoat: 1.0,
    clearcoatRoughness: 0.1,
    attenuationDistance: 0.5,
    attenuationColor: 0xffffff
  },
  metal: {
    metalness: 1.0,
    roughness: 0.2,
    clearcoat: 0.8,
    clearcoatRoughness: 0.2,
    transparent: false,
    opacity: 1.0
  },
  plastic: {
    metalness: 0.0,
    roughness: 0.3,
    clearcoat: 0.4,
    transparent: false,
    opacity: 1.0
  },
  crystal: {
    metalness: 0.1,
    roughness: 0.0,
    transmission: 1.0,
    thickness: 1.0,
    ior: 2.4,
    transparent: true,
    opacity: 0.3,
    envMapIntensity: 2.0,
    clearcoat: 1.0,
    clearcoatRoughness: 0.0,
    attenuationDistance: 0.2,
    attenuationColor: 0xffffff
  },
  holographic: {
    metalness: 0.8,
    roughness: 0.2,
    transmission: 0.5,
    thickness: 0.5,
    ior: 1.7,
    transparent: true,
    opacity: 0.7,
    envMapIntensity: 2.0,
    clearcoat: 1.0,
    clearcoatRoughness: 0.1,
    attenuationDistance: 0.3,
    attenuationColor: 0x88ff88,
    iridescence: 1.0,
    iridescenceIOR: 2.0,
    sheen: 1.0,
    sheenRoughness: 0.4,
    sheenColor: 0x88ff88,
    glow: true
  },
  neon: {
    metalness: 0.2,
    roughness: 0.1,
    transmission: 0.9,
    thickness: 0.2,
    ior: 1.6,
    transparent: true,
    opacity: 0.6,
    envMapIntensity: 3.0,
    emissive: 0xff00ff,
    emissiveIntensity: 2.0,
    glow: true
  },
  pearl: {
    metalness: 0.7,
    roughness: 0.1,
    clearcoat: 1.0,
    clearcoatRoughness: 0.1,
    sheen: 1.0,
    sheenRoughness: 0.3,
    sheenColor: 0xffffff,
    iridescence: 0.8,
    iridescenceIOR: 1.5
  },
  chrome: {
    metalness: 1.0,
    roughness: 0.0,
    envMapIntensity: 2.5,
    clearcoat: 1.0,
    clearcoatRoughness: 0.0,
    opacity: 1.0
  },
  opal: {
    metalness: 0.1,
    roughness: 0.3,
    transmission: 0.6,
    thickness: 0.5,
    ior: 1.9,
    transparent: true,
    opacity: 0.7,
    iridescence: 1.0,
    iridescenceIOR: 2.2,
    sheen: 1.0,
    sheenRoughness: 0.2,
    sheenColor: 0xffffff,
    attenuationColor: 0xaaccff
  },
  liquid: {
    metalness: 0.0,
    roughness: 0.0,
    transmission: 1.0,
    thickness: 2.0,
    ior: 1.33,
    transparent: true,
    opacity: 0.6,
    envMapIntensity: 1.2,
    clearcoat: 0.5,
    attenuationDistance: 1.0,
    attenuationColor: 0x00ffff
  },
  plasma: {
    metalness: 0.3,
    roughness: 0.2,
    transmission: 0.5,
    thickness: 0.2,
    ior: 2.0,
    transparent: true,
    opacity: 0.7,
    emissive: 0x88ff88,
    emissiveIntensity: 2.0,
    envMapIntensity: 2.0,
    glow: true
  },
  rainbow: {
    metalness: 0.8,
    roughness: 0.2,
    clearcoat: 1.0,
    clearcoatRoughness: 0.2,
    iridescence: 1.0,
    iridescenceIOR: 2.0,
    sheen: 1.0,
    sheenRoughness: 0.2,
    sheenColor: 0xffffff
  }
};